// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.21.12
// source: account.proto

package gvproto

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"

	_ "embed"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientType int32

const (
	ClientType_UNKNOWN_CLIENT_TYPE ClientType = 0
	ClientType_GV_WEB              ClientType = 3
)

// Enum value maps for ClientType.
var (
	ClientType_name = map[int32]string{
		0: "UNKNOWN_CLIENT_TYPE",
		3: "GV_WEB",
	}
	ClientType_value = map[string]int32{
		"UNKNOWN_CLIENT_TYPE": 0,
		"GV_WEB":              3,
	}
)

func (x ClientType) Enum() *ClientType {
	p := new(ClientType)
	*p = x
	return p
}

func (x ClientType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientType) Descriptor() protoreflect.EnumDescriptor {
	return file_account_proto_enumTypes[0].Descriptor()
}

func (ClientType) Type() protoreflect.EnumType {
	return &file_account_proto_enumTypes[0]
}

func (x ClientType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientType.Descriptor instead.
func (ClientType) EnumDescriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{0}
}

type ClientSetting int32

const (
	ClientSetting_UNKNOWN_CLIENT_SETTING ClientSetting = 0
	ClientSetting_DISABLED               ClientSetting = 1
	ClientSetting_ENABLED                ClientSetting = 2
)

// Enum value maps for ClientSetting.
var (
	ClientSetting_name = map[int32]string{
		0: "UNKNOWN_CLIENT_SETTING",
		1: "DISABLED",
		2: "ENABLED",
	}
	ClientSetting_value = map[string]int32{
		"UNKNOWN_CLIENT_SETTING": 0,
		"DISABLED":               1,
		"ENABLED":                2,
	}
)

func (x ClientSetting) Enum() *ClientSetting {
	p := new(ClientSetting)
	*p = x
	return p
}

func (x ClientSetting) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientSetting) Descriptor() protoreflect.EnumDescriptor {
	return file_account_proto_enumTypes[1].Descriptor()
}

func (ClientSetting) Type() protoreflect.EnumType {
	return &file_account_proto_enumTypes[1]
}

func (x ClientSetting) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientSetting.Descriptor instead.
func (ClientSetting) EnumDescriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{1}
}

type ApplicabilityLevel int32

const (
	ApplicabilityLevel_UNKNOWN_APPLICABILITY_LEVEL ApplicabilityLevel = 0
	ApplicabilityLevel_APPLICABLE                  ApplicabilityLevel = 1
	ApplicabilityLevel_NOT_APPLICABLE_HIDDEN       ApplicabilityLevel = 2
)

// Enum value maps for ApplicabilityLevel.
var (
	ApplicabilityLevel_name = map[int32]string{
		0: "UNKNOWN_APPLICABILITY_LEVEL",
		1: "APPLICABLE",
		2: "NOT_APPLICABLE_HIDDEN",
	}
	ApplicabilityLevel_value = map[string]int32{
		"UNKNOWN_APPLICABILITY_LEVEL": 0,
		"APPLICABLE":                  1,
		"NOT_APPLICABLE_HIDDEN":       2,
	}
)

func (x ApplicabilityLevel) Enum() *ApplicabilityLevel {
	p := new(ApplicabilityLevel)
	*p = x
	return p
}

func (x ApplicabilityLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApplicabilityLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_account_proto_enumTypes[2].Descriptor()
}

func (ApplicabilityLevel) Type() protoreflect.EnumType {
	return &file_account_proto_enumTypes[2]
}

func (x ApplicabilityLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApplicabilityLevel.Descriptor instead.
func (ApplicabilityLevel) EnumDescriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{2}
}

type SupportLevel int32

const (
	SupportLevel_UNKNOWN_SUPPORT_LEVEL   SupportLevel = 0
	SupportLevel_SUPPORTED_FOR_ACCOUNT   SupportLevel = 1
	SupportLevel_UNSUPPORTED_FOR_ACCOUNT SupportLevel = 2
)

// Enum value maps for SupportLevel.
var (
	SupportLevel_name = map[int32]string{
		0: "UNKNOWN_SUPPORT_LEVEL",
		1: "SUPPORTED_FOR_ACCOUNT",
		2: "UNSUPPORTED_FOR_ACCOUNT",
	}
	SupportLevel_value = map[string]int32{
		"UNKNOWN_SUPPORT_LEVEL":   0,
		"SUPPORTED_FOR_ACCOUNT":   1,
		"UNSUPPORTED_FOR_ACCOUNT": 2,
	}
)

func (x SupportLevel) Enum() *SupportLevel {
	p := new(SupportLevel)
	*p = x
	return p
}

func (x SupportLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SupportLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_account_proto_enumTypes[3].Descriptor()
}

func (SupportLevel) Type() protoreflect.EnumType {
	return &file_account_proto_enumTypes[3]
}

func (x SupportLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SupportLevel.Descriptor instead.
func (SupportLevel) EnumDescriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{3}
}

type CallAsPhone_DisplayHint int32

const (
	CallAsPhone_UNKNOWN_DISPLAY_HINT CallAsPhone_DisplayHint = 0
	CallAsPhone_DIRECT               CallAsPhone_DisplayHint = 3
)

// Enum value maps for CallAsPhone_DisplayHint.
var (
	CallAsPhone_DisplayHint_name = map[int32]string{
		0: "UNKNOWN_DISPLAY_HINT",
		3: "DIRECT",
	}
	CallAsPhone_DisplayHint_value = map[string]int32{
		"UNKNOWN_DISPLAY_HINT": 0,
		"DIRECT":               3,
	}
)

func (x CallAsPhone_DisplayHint) Enum() *CallAsPhone_DisplayHint {
	p := new(CallAsPhone_DisplayHint)
	*p = x
	return p
}

func (x CallAsPhone_DisplayHint) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallAsPhone_DisplayHint) Descriptor() protoreflect.EnumDescriptor {
	return file_account_proto_enumTypes[4].Descriptor()
}

func (CallAsPhone_DisplayHint) Type() protoreflect.EnumType {
	return &file_account_proto_enumTypes[4]
}

func (x CallAsPhone_DisplayHint) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CallAsPhone_DisplayHint.Descriptor instead.
func (CallAsPhone_DisplayHint) EnumDescriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{7, 0}
}

type AccountPhone_Branding int32

const (
	AccountPhone_UNKNOWN_BRANDING AccountPhone_Branding = 0
	AccountPhone_GOOGLE_VOICE     AccountPhone_Branding = 1
)

// Enum value maps for AccountPhone_Branding.
var (
	AccountPhone_Branding_name = map[int32]string{
		0: "UNKNOWN_BRANDING",
		1: "GOOGLE_VOICE",
	}
	AccountPhone_Branding_value = map[string]int32{
		"UNKNOWN_BRANDING": 0,
		"GOOGLE_VOICE":     1,
	}
)

func (x AccountPhone_Branding) Enum() *AccountPhone_Branding {
	p := new(AccountPhone_Branding)
	*p = x
	return p
}

func (x AccountPhone_Branding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountPhone_Branding) Descriptor() protoreflect.EnumDescriptor {
	return file_account_proto_enumTypes[5].Descriptor()
}

func (AccountPhone_Branding) Type() protoreflect.EnumType {
	return &file_account_proto_enumTypes[5]
}

func (x AccountPhone_Branding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountPhone_Branding.Descriptor instead.
func (AccountPhone_Branding) EnumDescriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{8, 0}
}

type Account struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrimaryDestinationID string         `protobuf:"bytes,1,opt,name=primaryDestinationID,proto3" json:"primaryDestinationID,omitempty"`
	Phones               []*Phone       `protobuf:"bytes,3,rep,name=phones,proto3" json:"phones,omitempty"`
	Communication        *Communication `protobuf:"bytes,4,opt,name=communication,proto3" json:"communication,omitempty"`
	// Integration integration = 6;
	// ClientAccess clientAccess = 7;
	// Promos promos = 8;
	// Accessibility accessibility = 9;
	// Status status = 10;
	// DisplayHints displayHints = 11;
	// Address address = 12;
	Version *AccountVersion `protobuf:"bytes,13,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetPrimaryDestinationID() string {
	if x != nil {
		return x.PrimaryDestinationID
	}
	return ""
}

func (x *Account) GetPhones() []*Phone {
	if x != nil {
		return x.Phones
	}
	return nil
}

func (x *Account) GetCommunication() *Communication {
	if x != nil {
		return x.Communication
	}
	return nil
}

func (x *Account) GetVersion() *AccountVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

type AccountVersion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VersionToken string `protobuf:"bytes,1,opt,name=versionToken,proto3" json:"versionToken,omitempty"`
}

func (x *AccountVersion) Reset() {
	*x = AccountVersion{}
	mi := &file_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountVersion) ProtoMessage() {}

func (x *AccountVersion) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountVersion.ProtoReflect.Descriptor instead.
func (*AccountVersion) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{1}
}

func (x *AccountVersion) GetVersionToken() string {
	if x != nil {
		return x.VersionToken
	}
	return ""
}

type Communication struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnableGlobalSpamFiltering bool                            `protobuf:"varint,1,opt,name=enableGlobalSpamFiltering,proto3" json:"enableGlobalSpamFiltering,omitempty"`
	DoNotDisturb              *Communication_DoNotDisturb     `protobuf:"bytes,2,opt,name=doNotDisturb,proto3" json:"doNotDisturb,omitempty"`
	Transcription             *Communication_Transcription    `protobuf:"bytes,3,opt,name=transcription,proto3" json:"transcription,omitempty"`
	SupportedActions          *Communication_SupportedActions `protobuf:"bytes,4,opt,name=supportedActions,proto3" json:"supportedActions,omitempty"`
	// MessagingSupport messagingSupport = 5;
	EnableInCallCommands bool `protobuf:"varint,6,opt,name=enableInCallCommands,proto3" json:"enableInCallCommands,omitempty"`
	// EmailForwardingModalities emailForwardingModalities = 8;
	// CallScreening callScreening = 9;
	DefaultOutgoingNumberRegionCode string `protobuf:"bytes,10,opt,name=defaultOutgoingNumberRegionCode,proto3" json:"defaultOutgoingNumberRegionCode,omitempty"`
	// VoicemailGreeting voicemailGreeting = 11;
	// VoIP voip = 12;
	// EmergencyCallbackMode emergencyCallbackMode = 13;
	EnableAnonymousOutboundCalls bool         `protobuf:"varint,14,opt,name=enableAnonymousOutboundCalls,proto3" json:"enableAnonymousOutboundCalls,omitempty"`
	UseDestinationIDAsCallerID   bool         `protobuf:"varint,15,opt,name=useDestinationIDAsCallerID,proto3" json:"useDestinationIDAsCallerID,omitempty"`
	DefaultOutboundCallerID      *PhoneNumber `protobuf:"bytes,16,opt,name=defaultOutboundCallerID,proto3" json:"defaultOutboundCallerID,omitempty"`
}

func (x *Communication) Reset() {
	*x = Communication{}
	mi := &file_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Communication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Communication) ProtoMessage() {}

func (x *Communication) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Communication.ProtoReflect.Descriptor instead.
func (*Communication) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{2}
}

func (x *Communication) GetEnableGlobalSpamFiltering() bool {
	if x != nil {
		return x.EnableGlobalSpamFiltering
	}
	return false
}

func (x *Communication) GetDoNotDisturb() *Communication_DoNotDisturb {
	if x != nil {
		return x.DoNotDisturb
	}
	return nil
}

func (x *Communication) GetTranscription() *Communication_Transcription {
	if x != nil {
		return x.Transcription
	}
	return nil
}

func (x *Communication) GetSupportedActions() *Communication_SupportedActions {
	if x != nil {
		return x.SupportedActions
	}
	return nil
}

func (x *Communication) GetEnableInCallCommands() bool {
	if x != nil {
		return x.EnableInCallCommands
	}
	return false
}

func (x *Communication) GetDefaultOutgoingNumberRegionCode() string {
	if x != nil {
		return x.DefaultOutgoingNumberRegionCode
	}
	return ""
}

func (x *Communication) GetEnableAnonymousOutboundCalls() bool {
	if x != nil {
		return x.EnableAnonymousOutboundCalls
	}
	return false
}

func (x *Communication) GetUseDestinationIDAsCallerID() bool {
	if x != nil {
		return x.UseDestinationIDAsCallerID
	}
	return false
}

func (x *Communication) GetDefaultOutboundCallerID() *PhoneNumber {
	if x != nil {
		return x.DefaultOutboundCallerID
	}
	return nil
}

type Phone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountPhone            *AccountPhone            `protobuf:"bytes,1,opt,name=accountPhone,proto3" json:"accountPhone,omitempty"`
	LinkedPhoneRestrictions *LinkedPhoneRestrictions `protobuf:"bytes,4,opt,name=linkedPhoneRestrictions,proto3" json:"linkedPhoneRestrictions,omitempty"`
	LinkedVoIPDevices       []*LinkedVoIPDevice      `protobuf:"bytes,5,rep,name=linkedVoIPDevices,proto3" json:"linkedVoIPDevices,omitempty"`
	DefaultVoIPSettings     *DefaultVoIPSettings     `protobuf:"bytes,6,opt,name=defaultVoIPSettings,proto3" json:"defaultVoIPSettings,omitempty"`
	CallAsPhone             []*CallAsPhone           `protobuf:"bytes,7,rep,name=callAsPhone,proto3" json:"callAsPhone,omitempty"`
	SignupForNewNumber      bool                     `protobuf:"varint,8,opt,name=signupForNewNumber,proto3" json:"signupForNewNumber,omitempty"`
	EligibleForSelfSignup   bool                     `protobuf:"varint,9,opt,name=eligibleForSelfSignup,proto3" json:"eligibleForSelfSignup,omitempty"`
	EligibleForAdminSignup  bool                     `protobuf:"varint,10,opt,name=eligibleForAdminSignup,proto3" json:"eligibleForAdminSignup,omitempty"`
}

func (x *Phone) Reset() {
	*x = Phone{}
	mi := &file_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Phone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Phone) ProtoMessage() {}

func (x *Phone) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Phone.ProtoReflect.Descriptor instead.
func (*Phone) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{3}
}

func (x *Phone) GetAccountPhone() *AccountPhone {
	if x != nil {
		return x.AccountPhone
	}
	return nil
}

func (x *Phone) GetLinkedPhoneRestrictions() *LinkedPhoneRestrictions {
	if x != nil {
		return x.LinkedPhoneRestrictions
	}
	return nil
}

func (x *Phone) GetLinkedVoIPDevices() []*LinkedVoIPDevice {
	if x != nil {
		return x.LinkedVoIPDevices
	}
	return nil
}

func (x *Phone) GetDefaultVoIPSettings() *DefaultVoIPSettings {
	if x != nil {
		return x.DefaultVoIPSettings
	}
	return nil
}

func (x *Phone) GetCallAsPhone() []*CallAsPhone {
	if x != nil {
		return x.CallAsPhone
	}
	return nil
}

func (x *Phone) GetSignupForNewNumber() bool {
	if x != nil {
		return x.SignupForNewNumber
	}
	return false
}

func (x *Phone) GetEligibleForSelfSignup() bool {
	if x != nil {
		return x.EligibleForSelfSignup
	}
	return false
}

func (x *Phone) GetEligibleForAdminSignup() bool {
	if x != nil {
		return x.EligibleForAdminSignup
	}
	return false
}

type LinkedPhoneRestrictions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CountryWhitelist *LinkedPhoneRestrictions_CountryWhitelist `protobuf:"bytes,1,opt,name=countryWhitelist,proto3" json:"countryWhitelist,omitempty"`
}

func (x *LinkedPhoneRestrictions) Reset() {
	*x = LinkedPhoneRestrictions{}
	mi := &file_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkedPhoneRestrictions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkedPhoneRestrictions) ProtoMessage() {}

func (x *LinkedPhoneRestrictions) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkedPhoneRestrictions.ProtoReflect.Descriptor instead.
func (*LinkedPhoneRestrictions) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{4}
}

func (x *LinkedPhoneRestrictions) GetCountryWhitelist() *LinkedPhoneRestrictions_CountryWhitelist {
	if x != nil {
		return x.CountryWhitelist
	}
	return nil
}

type LinkedVoIPDevice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SIPDeviceID string     `protobuf:"bytes,1,opt,name=SIPDeviceID,proto3" json:"SIPDeviceID,omitempty"`
	ClientType  ClientType `protobuf:"varint,2,opt,name=clientType,proto3,enum=account.ClientType" json:"clientType,omitempty"`
	Name        string     `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// TODO forwardingModalities
	InboundCalls  ClientSetting `protobuf:"varint,6,opt,name=inboundCalls,proto3,enum=account.ClientSetting" json:"inboundCalls,omitempty"`
	OutboundCalls ClientSetting `protobuf:"varint,7,opt,name=outboundCalls,proto3,enum=account.ClientSetting" json:"outboundCalls,omitempty"`
}

func (x *LinkedVoIPDevice) Reset() {
	*x = LinkedVoIPDevice{}
	mi := &file_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkedVoIPDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkedVoIPDevice) ProtoMessage() {}

func (x *LinkedVoIPDevice) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkedVoIPDevice.ProtoReflect.Descriptor instead.
func (*LinkedVoIPDevice) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{5}
}

func (x *LinkedVoIPDevice) GetSIPDeviceID() string {
	if x != nil {
		return x.SIPDeviceID
	}
	return ""
}

func (x *LinkedVoIPDevice) GetClientType() ClientType {
	if x != nil {
		return x.ClientType
	}
	return ClientType_UNKNOWN_CLIENT_TYPE
}

func (x *LinkedVoIPDevice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LinkedVoIPDevice) GetInboundCalls() ClientSetting {
	if x != nil {
		return x.InboundCalls
	}
	return ClientSetting_UNKNOWN_CLIENT_SETTING
}

func (x *LinkedVoIPDevice) GetOutboundCalls() ClientSetting {
	if x != nil {
		return x.OutboundCalls
	}
	return ClientSetting_UNKNOWN_CLIENT_SETTING
}

type DefaultVoIPSettings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PreferVoIP ClientSetting `protobuf:"varint,1,opt,name=preferVoIP,proto3,enum=account.ClientSetting" json:"preferVoIP,omitempty"`
}

func (x *DefaultVoIPSettings) Reset() {
	*x = DefaultVoIPSettings{}
	mi := &file_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefaultVoIPSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultVoIPSettings) ProtoMessage() {}

func (x *DefaultVoIPSettings) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultVoIPSettings.ProtoReflect.Descriptor instead.
func (*DefaultVoIPSettings) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{6}
}

func (x *DefaultVoIPSettings) GetPreferVoIP() ClientSetting {
	if x != nil {
		return x.PreferVoIP
	}
	return ClientSetting_UNKNOWN_CLIENT_SETTING
}

type CallAsPhone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PhoneNumber      *PhoneNumber            `protobuf:"bytes,1,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	InitialSelection bool                    `protobuf:"varint,2,opt,name=initialSelection,proto3" json:"initialSelection,omitempty"`
	DisplayHint      CallAsPhone_DisplayHint `protobuf:"varint,4,opt,name=displayHint,proto3,enum=account.CallAsPhone_DisplayHint" json:"displayHint,omitempty"`
}

func (x *CallAsPhone) Reset() {
	*x = CallAsPhone{}
	mi := &file_account_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallAsPhone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallAsPhone) ProtoMessage() {}

func (x *CallAsPhone) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallAsPhone.ProtoReflect.Descriptor instead.
func (*CallAsPhone) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{7}
}

func (x *CallAsPhone) GetPhoneNumber() *PhoneNumber {
	if x != nil {
		return x.PhoneNumber
	}
	return nil
}

func (x *CallAsPhone) GetInitialSelection() bool {
	if x != nil {
		return x.InitialSelection
	}
	return false
}

func (x *CallAsPhone) GetDisplayHint() CallAsPhone_DisplayHint {
	if x != nil {
		return x.DisplayHint
	}
	return CallAsPhone_UNKNOWN_DISPLAY_HINT
}

type AccountPhone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PhoneNumber                      *PhoneNumber                      `protobuf:"bytes,1,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	DefaultForOutboundCommunications bool                              `protobuf:"varint,2,opt,name=defaultForOutboundCommunications,proto3" json:"defaultForOutboundCommunications,omitempty"`
	Branding                         AccountPhone_Branding             `protobuf:"varint,3,opt,name=branding,proto3,enum=account.AccountPhone_Branding" json:"branding,omitempty"`
	SupportedActions                 *AccountPhone_SupportedActions    `protobuf:"bytes,4,opt,name=supportedActions,proto3" json:"supportedActions,omitempty"`
	IsPermanent                      bool                              `protobuf:"varint,6,opt,name=isPermanent,proto3" json:"isPermanent,omitempty"`
	ApplicabilityLevels              *AccountPhone_ApplicabilityLevels `protobuf:"bytes,203,opt,name=applicabilityLevels,proto3" json:"applicabilityLevels,omitempty"`
}

func (x *AccountPhone) Reset() {
	*x = AccountPhone{}
	mi := &file_account_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountPhone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountPhone) ProtoMessage() {}

func (x *AccountPhone) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountPhone.ProtoReflect.Descriptor instead.
func (*AccountPhone) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{8}
}

func (x *AccountPhone) GetPhoneNumber() *PhoneNumber {
	if x != nil {
		return x.PhoneNumber
	}
	return nil
}

func (x *AccountPhone) GetDefaultForOutboundCommunications() bool {
	if x != nil {
		return x.DefaultForOutboundCommunications
	}
	return false
}

func (x *AccountPhone) GetBranding() AccountPhone_Branding {
	if x != nil {
		return x.Branding
	}
	return AccountPhone_UNKNOWN_BRANDING
}

func (x *AccountPhone) GetSupportedActions() *AccountPhone_SupportedActions {
	if x != nil {
		return x.SupportedActions
	}
	return nil
}

func (x *AccountPhone) GetIsPermanent() bool {
	if x != nil {
		return x.IsPermanent
	}
	return false
}

func (x *AccountPhone) GetApplicabilityLevels() *AccountPhone_ApplicabilityLevels {
	if x != nil {
		return x.ApplicabilityLevels
	}
	return nil
}

type PhoneNumber struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	E164 string `protobuf:"bytes,1,opt,name=e164,proto3" json:"e164,omitempty"`
}

func (x *PhoneNumber) Reset() {
	*x = PhoneNumber{}
	mi := &file_account_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhoneNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneNumber) ProtoMessage() {}

func (x *PhoneNumber) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneNumber.ProtoReflect.Descriptor instead.
func (*PhoneNumber) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{9}
}

func (x *PhoneNumber) GetE164() string {
	if x != nil {
		return x.E164
	}
	return ""
}

type Communication_DoNotDisturb struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enabled                   bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	EnableDndOutsideWorkHours bool `protobuf:"varint,2,opt,name=enableDndOutsideWorkHours,proto3" json:"enableDndOutsideWorkHours,omitempty"`
	EnableDndOutOfOffice      bool `protobuf:"varint,3,opt,name=enableDndOutOfOffice,proto3" json:"enableDndOutOfOffice,omitempty"`
	// DndReason dndReason = 4 or 5;
	// unknown unknown = 5 or 4;
	// InvertedClientSetting allLines = 6;
	// InvertedClientSetting directLines = 7;
	// InvertedClientSetting allRgLines = 8;
	ApplicabilityMask   *Communication_DoNotDisturb_ApplicabilityMask   `protobuf:"bytes,202,opt,name=applicabilityMask,proto3" json:"applicabilityMask,omitempty"`
	ApplicabilityLevels *Communication_DoNotDisturb_ApplicabilityLevels `protobuf:"bytes,203,opt,name=applicabilityLevels,proto3" json:"applicabilityLevels,omitempty"`
}

func (x *Communication_DoNotDisturb) Reset() {
	*x = Communication_DoNotDisturb{}
	mi := &file_account_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Communication_DoNotDisturb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Communication_DoNotDisturb) ProtoMessage() {}

func (x *Communication_DoNotDisturb) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Communication_DoNotDisturb.ProtoReflect.Descriptor instead.
func (*Communication_DoNotDisturb) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Communication_DoNotDisturb) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Communication_DoNotDisturb) GetEnableDndOutsideWorkHours() bool {
	if x != nil {
		return x.EnableDndOutsideWorkHours
	}
	return false
}

func (x *Communication_DoNotDisturb) GetEnableDndOutOfOffice() bool {
	if x != nil {
		return x.EnableDndOutOfOffice
	}
	return false
}

func (x *Communication_DoNotDisturb) GetApplicabilityMask() *Communication_DoNotDisturb_ApplicabilityMask {
	if x != nil {
		return x.ApplicabilityMask
	}
	return nil
}

func (x *Communication_DoNotDisturb) GetApplicabilityLevels() *Communication_DoNotDisturb_ApplicabilityLevels {
	if x != nil {
		return x.ApplicabilityLevels
	}
	return nil
}

type Communication_Transcription struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnableForVoicemail        bool                                             `protobuf:"varint,1,opt,name=enableForVoicemail,proto3" json:"enableForVoicemail,omitempty"`
	ConsentsToMachineAnalysis bool                                             `protobuf:"varint,2,opt,name=consentsToMachineAnalysis,proto3" json:"consentsToMachineAnalysis,omitempty"`
	ApplicabilityMask         *Communication_Transcription_ApplicabilityMask   `protobuf:"bytes,202,opt,name=applicabilityMask,proto3" json:"applicabilityMask,omitempty"`
	ApplicabilityLevels       *Communication_Transcription_ApplicabilityLevels `protobuf:"bytes,203,opt,name=applicabilityLevels,proto3" json:"applicabilityLevels,omitempty"`
}

func (x *Communication_Transcription) Reset() {
	*x = Communication_Transcription{}
	mi := &file_account_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Communication_Transcription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Communication_Transcription) ProtoMessage() {}

func (x *Communication_Transcription) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Communication_Transcription.ProtoReflect.Descriptor instead.
func (*Communication_Transcription) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Communication_Transcription) GetEnableForVoicemail() bool {
	if x != nil {
		return x.EnableForVoicemail
	}
	return false
}

func (x *Communication_Transcription) GetConsentsToMachineAnalysis() bool {
	if x != nil {
		return x.ConsentsToMachineAnalysis
	}
	return false
}

func (x *Communication_Transcription) GetApplicabilityMask() *Communication_Transcription_ApplicabilityMask {
	if x != nil {
		return x.ApplicabilityMask
	}
	return nil
}

func (x *Communication_Transcription) GetApplicabilityLevels() *Communication_Transcription_ApplicabilityLevels {
	if x != nil {
		return x.ApplicabilityLevels
	}
	return nil
}

type Communication_SupportedActions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClickToCall                         bool                                                `protobuf:"varint,1,opt,name=clickToCall,proto3" json:"clickToCall,omitempty"`
	SendSMS                             SupportLevel                                        `protobuf:"varint,2,opt,name=sendSMS,proto3,enum=account.SupportLevel" json:"sendSMS,omitempty"`
	InterceptAndroidDialerCalling       bool                                                `protobuf:"varint,3,opt,name=interceptAndroidDialerCalling,proto3" json:"interceptAndroidDialerCalling,omitempty"`
	MakeEmergencyVoIPCall               SupportLevel                                        `protobuf:"varint,4,opt,name=makeEmergencyVoIPCall,proto3,enum=account.SupportLevel" json:"makeEmergencyVoIPCall,omitempty"`
	EmergencyVoIPCallSupportedCountries []string                                            `protobuf:"bytes,5,rep,name=emergencyVoIPCallSupportedCountries,proto3" json:"emergencyVoIPCallSupportedCountries,omitempty"`
	MakeShortCodeProxyCall              SupportLevel                                        `protobuf:"varint,6,opt,name=makeShortCodeProxyCall,proto3,enum=account.SupportLevel" json:"makeShortCodeProxyCall,omitempty"`
	TransferCall                        SupportLevel                                        `protobuf:"varint,7,opt,name=transferCall,proto3,enum=account.SupportLevel" json:"transferCall,omitempty"`
	UseHangoutsForCalling               SupportLevel                                        `protobuf:"varint,8,opt,name=useHangoutsForCalling,proto3,enum=account.SupportLevel" json:"useHangoutsForCalling,omitempty"`
	AllowAllShortCodeDialing            SupportLevel                                        `protobuf:"varint,9,opt,name=allowAllShortCodeDialing,proto3,enum=account.SupportLevel" json:"allowAllShortCodeDialing,omitempty"`
	AllowArbitraryPhoneNumberDialing    SupportLevel                                        `protobuf:"varint,10,opt,name=allowArbitraryPhoneNumberDialing,proto3,enum=account.SupportLevel" json:"allowArbitraryPhoneNumberDialing,omitempty"` //AllowTransferCallingSupportLevel allowTransferCalling = 11;
	ApplicabilityLevels                 *Communication_SupportedActions_ApplicabilityLevels `protobuf:"bytes,203,opt,name=applicabilityLevels,proto3" json:"applicabilityLevels,omitempty"`
}

func (x *Communication_SupportedActions) Reset() {
	*x = Communication_SupportedActions{}
	mi := &file_account_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Communication_SupportedActions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Communication_SupportedActions) ProtoMessage() {}

func (x *Communication_SupportedActions) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Communication_SupportedActions.ProtoReflect.Descriptor instead.
func (*Communication_SupportedActions) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{2, 2}
}

func (x *Communication_SupportedActions) GetClickToCall() bool {
	if x != nil {
		return x.ClickToCall
	}
	return false
}

func (x *Communication_SupportedActions) GetSendSMS() SupportLevel {
	if x != nil {
		return x.SendSMS
	}
	return SupportLevel_UNKNOWN_SUPPORT_LEVEL
}

func (x *Communication_SupportedActions) GetInterceptAndroidDialerCalling() bool {
	if x != nil {
		return x.InterceptAndroidDialerCalling
	}
	return false
}

func (x *Communication_SupportedActions) GetMakeEmergencyVoIPCall() SupportLevel {
	if x != nil {
		return x.MakeEmergencyVoIPCall
	}
	return SupportLevel_UNKNOWN_SUPPORT_LEVEL
}

func (x *Communication_SupportedActions) GetEmergencyVoIPCallSupportedCountries() []string {
	if x != nil {
		return x.EmergencyVoIPCallSupportedCountries
	}
	return nil
}

func (x *Communication_SupportedActions) GetMakeShortCodeProxyCall() SupportLevel {
	if x != nil {
		return x.MakeShortCodeProxyCall
	}
	return SupportLevel_UNKNOWN_SUPPORT_LEVEL
}

func (x *Communication_SupportedActions) GetTransferCall() SupportLevel {
	if x != nil {
		return x.TransferCall
	}
	return SupportLevel_UNKNOWN_SUPPORT_LEVEL
}

func (x *Communication_SupportedActions) GetUseHangoutsForCalling() SupportLevel {
	if x != nil {
		return x.UseHangoutsForCalling
	}
	return SupportLevel_UNKNOWN_SUPPORT_LEVEL
}

func (x *Communication_SupportedActions) GetAllowAllShortCodeDialing() SupportLevel {
	if x != nil {
		return x.AllowAllShortCodeDialing
	}
	return SupportLevel_UNKNOWN_SUPPORT_LEVEL
}

func (x *Communication_SupportedActions) GetAllowArbitraryPhoneNumberDialing() SupportLevel {
	if x != nil {
		return x.AllowArbitraryPhoneNumberDialing
	}
	return SupportLevel_UNKNOWN_SUPPORT_LEVEL
}

func (x *Communication_SupportedActions) GetApplicabilityLevels() *Communication_SupportedActions_ApplicabilityLevels {
	if x != nil {
		return x.ApplicabilityLevels
	}
	return nil
}

type Communication_DoNotDisturb_ApplicabilityMask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
}

func (x *Communication_DoNotDisturb_ApplicabilityMask) Reset() {
	*x = Communication_DoNotDisturb_ApplicabilityMask{}
	mi := &file_account_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Communication_DoNotDisturb_ApplicabilityMask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Communication_DoNotDisturb_ApplicabilityMask) ProtoMessage() {}

func (x *Communication_DoNotDisturb_ApplicabilityMask) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Communication_DoNotDisturb_ApplicabilityMask.ProtoReflect.Descriptor instead.
func (*Communication_DoNotDisturb_ApplicabilityMask) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *Communication_DoNotDisturb_ApplicabilityMask) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type Communication_DoNotDisturb_ApplicabilityLevels struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enabled                   ApplicabilityLevel `protobuf:"varint,1,opt,name=enabled,proto3,enum=account.ApplicabilityLevel" json:"enabled,omitempty"`
	Expiration                ApplicabilityLevel `protobuf:"varint,2,opt,name=expiration,proto3,enum=account.ApplicabilityLevel" json:"expiration,omitempty"`
	EnableDndOutsideWorkHours ApplicabilityLevel `protobuf:"varint,3,opt,name=enableDndOutsideWorkHours,proto3,enum=account.ApplicabilityLevel" json:"enableDndOutsideWorkHours,omitempty"`
	EnableDndOutOfOffice      ApplicabilityLevel `protobuf:"varint,4,opt,name=enableDndOutOfOffice,proto3,enum=account.ApplicabilityLevel" json:"enableDndOutOfOffice,omitempty"`
	DndReason                 ApplicabilityLevel `protobuf:"varint,5,opt,name=dndReason,proto3,enum=account.ApplicabilityLevel" json:"dndReason,omitempty"`
	AllLines                  ApplicabilityLevel `protobuf:"varint,6,opt,name=allLines,proto3,enum=account.ApplicabilityLevel" json:"allLines,omitempty"`
	DirectLines               ApplicabilityLevel `protobuf:"varint,7,opt,name=directLines,proto3,enum=account.ApplicabilityLevel" json:"directLines,omitempty"`
	AllRgLines                ApplicabilityLevel `protobuf:"varint,8,opt,name=allRgLines,proto3,enum=account.ApplicabilityLevel" json:"allRgLines,omitempty"`
}

func (x *Communication_DoNotDisturb_ApplicabilityLevels) Reset() {
	*x = Communication_DoNotDisturb_ApplicabilityLevels{}
	mi := &file_account_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Communication_DoNotDisturb_ApplicabilityLevels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Communication_DoNotDisturb_ApplicabilityLevels) ProtoMessage() {}

func (x *Communication_DoNotDisturb_ApplicabilityLevels) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Communication_DoNotDisturb_ApplicabilityLevels.ProtoReflect.Descriptor instead.
func (*Communication_DoNotDisturb_ApplicabilityLevels) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{2, 0, 1}
}

func (x *Communication_DoNotDisturb_ApplicabilityLevels) GetEnabled() ApplicabilityLevel {
	if x != nil {
		return x.Enabled
	}
	return ApplicabilityLevel_UNKNOWN_APPLICABILITY_LEVEL
}

func (x *Communication_DoNotDisturb_ApplicabilityLevels) GetExpiration() ApplicabilityLevel {
	if x != nil {
		return x.Expiration
	}
	return ApplicabilityLevel_UNKNOWN_APPLICABILITY_LEVEL
}

func (x *Communication_DoNotDisturb_ApplicabilityLevels) GetEnableDndOutsideWorkHours() ApplicabilityLevel {
	if x != nil {
		return x.EnableDndOutsideWorkHours
	}
	return ApplicabilityLevel_UNKNOWN_APPLICABILITY_LEVEL
}

func (x *Communication_DoNotDisturb_ApplicabilityLevels) GetEnableDndOutOfOffice() ApplicabilityLevel {
	if x != nil {
		return x.EnableDndOutOfOffice
	}
	return ApplicabilityLevel_UNKNOWN_APPLICABILITY_LEVEL
}

func (x *Communication_DoNotDisturb_ApplicabilityLevels) GetDndReason() ApplicabilityLevel {
	if x != nil {
		return x.DndReason
	}
	return ApplicabilityLevel_UNKNOWN_APPLICABILITY_LEVEL
}

func (x *Communication_DoNotDisturb_ApplicabilityLevels) GetAllLines() ApplicabilityLevel {
	if x != nil {
		return x.AllLines
	}
	return ApplicabilityLevel_UNKNOWN_APPLICABILITY_LEVEL
}

func (x *Communication_DoNotDisturb_ApplicabilityLevels) GetDirectLines() ApplicabilityLevel {
	if x != nil {
		return x.DirectLines
	}
	return ApplicabilityLevel_UNKNOWN_APPLICABILITY_LEVEL
}

func (x *Communication_DoNotDisturb_ApplicabilityLevels) GetAllRgLines() ApplicabilityLevel {
	if x != nil {
		return x.AllRgLines
	}
	return ApplicabilityLevel_UNKNOWN_APPLICABILITY_LEVEL
}

type Communication_Transcription_ApplicabilityMask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnableForVoicemail        bool `protobuf:"varint,1,opt,name=enableForVoicemail,proto3" json:"enableForVoicemail,omitempty"`
	ConsentsToMachineAnalysis bool `protobuf:"varint,2,opt,name=consentsToMachineAnalysis,proto3" json:"consentsToMachineAnalysis,omitempty"`
}

func (x *Communication_Transcription_ApplicabilityMask) Reset() {
	*x = Communication_Transcription_ApplicabilityMask{}
	mi := &file_account_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Communication_Transcription_ApplicabilityMask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Communication_Transcription_ApplicabilityMask) ProtoMessage() {}

func (x *Communication_Transcription_ApplicabilityMask) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Communication_Transcription_ApplicabilityMask.ProtoReflect.Descriptor instead.
func (*Communication_Transcription_ApplicabilityMask) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{2, 1, 0}
}

func (x *Communication_Transcription_ApplicabilityMask) GetEnableForVoicemail() bool {
	if x != nil {
		return x.EnableForVoicemail
	}
	return false
}

func (x *Communication_Transcription_ApplicabilityMask) GetConsentsToMachineAnalysis() bool {
	if x != nil {
		return x.ConsentsToMachineAnalysis
	}
	return false
}

type Communication_Transcription_ApplicabilityLevels struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnableForVoicemail        ApplicabilityLevel `protobuf:"varint,1,opt,name=enableForVoicemail,proto3,enum=account.ApplicabilityLevel" json:"enableForVoicemail,omitempty"`
	ConsentsToMachineAnalysis ApplicabilityLevel `protobuf:"varint,2,opt,name=consentsToMachineAnalysis,proto3,enum=account.ApplicabilityLevel" json:"consentsToMachineAnalysis,omitempty"`
}

func (x *Communication_Transcription_ApplicabilityLevels) Reset() {
	*x = Communication_Transcription_ApplicabilityLevels{}
	mi := &file_account_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Communication_Transcription_ApplicabilityLevels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Communication_Transcription_ApplicabilityLevels) ProtoMessage() {}

func (x *Communication_Transcription_ApplicabilityLevels) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Communication_Transcription_ApplicabilityLevels.ProtoReflect.Descriptor instead.
func (*Communication_Transcription_ApplicabilityLevels) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{2, 1, 1}
}

func (x *Communication_Transcription_ApplicabilityLevels) GetEnableForVoicemail() ApplicabilityLevel {
	if x != nil {
		return x.EnableForVoicemail
	}
	return ApplicabilityLevel_UNKNOWN_APPLICABILITY_LEVEL
}

func (x *Communication_Transcription_ApplicabilityLevels) GetConsentsToMachineAnalysis() ApplicabilityLevel {
	if x != nil {
		return x.ConsentsToMachineAnalysis
	}
	return ApplicabilityLevel_UNKNOWN_APPLICABILITY_LEVEL
}

type Communication_SupportedActions_ApplicabilityLevels struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UseHangoutsForCalling ApplicabilityLevel `protobuf:"varint,8,opt,name=useHangoutsForCalling,proto3,enum=account.ApplicabilityLevel" json:"useHangoutsForCalling,omitempty"`
}

func (x *Communication_SupportedActions_ApplicabilityLevels) Reset() {
	*x = Communication_SupportedActions_ApplicabilityLevels{}
	mi := &file_account_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Communication_SupportedActions_ApplicabilityLevels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Communication_SupportedActions_ApplicabilityLevels) ProtoMessage() {}

func (x *Communication_SupportedActions_ApplicabilityLevels) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Communication_SupportedActions_ApplicabilityLevels.ProtoReflect.Descriptor instead.
func (*Communication_SupportedActions_ApplicabilityLevels) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{2, 2, 0}
}

func (x *Communication_SupportedActions_ApplicabilityLevels) GetUseHangoutsForCalling() ApplicabilityLevel {
	if x != nil {
		return x.UseHangoutsForCalling
	}
	return ApplicabilityLevel_UNKNOWN_APPLICABILITY_LEVEL
}

type LinkedPhoneRestrictions_CountryWhitelist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RegionCode []string `protobuf:"bytes,1,rep,name=regionCode,proto3" json:"regionCode,omitempty"`
}

func (x *LinkedPhoneRestrictions_CountryWhitelist) Reset() {
	*x = LinkedPhoneRestrictions_CountryWhitelist{}
	mi := &file_account_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkedPhoneRestrictions_CountryWhitelist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkedPhoneRestrictions_CountryWhitelist) ProtoMessage() {}

func (x *LinkedPhoneRestrictions_CountryWhitelist) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkedPhoneRestrictions_CountryWhitelist.ProtoReflect.Descriptor instead.
func (*LinkedPhoneRestrictions_CountryWhitelist) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{4, 0}
}

func (x *LinkedPhoneRestrictions_CountryWhitelist) GetRegionCode() []string {
	if x != nil {
		return x.RegionCode
	}
	return nil
}

type AccountPhone_SupportedActions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Remove   bool `protobuf:"varint,1,opt,name=remove,proto3" json:"remove,omitempty"`
	Transfer bool `protobuf:"varint,2,opt,name=transfer,proto3" json:"transfer,omitempty"`
	Change   bool `protobuf:"varint,3,opt,name=change,proto3" json:"change,omitempty"`
	Lock     bool `protobuf:"varint,4,opt,name=lock,proto3" json:"lock,omitempty"`
	Unlock   bool `protobuf:"varint,5,opt,name=unlock,proto3" json:"unlock,omitempty"`
}

func (x *AccountPhone_SupportedActions) Reset() {
	*x = AccountPhone_SupportedActions{}
	mi := &file_account_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountPhone_SupportedActions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountPhone_SupportedActions) ProtoMessage() {}

func (x *AccountPhone_SupportedActions) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountPhone_SupportedActions.ProtoReflect.Descriptor instead.
func (*AccountPhone_SupportedActions) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{8, 0}
}

func (x *AccountPhone_SupportedActions) GetRemove() bool {
	if x != nil {
		return x.Remove
	}
	return false
}

func (x *AccountPhone_SupportedActions) GetTransfer() bool {
	if x != nil {
		return x.Transfer
	}
	return false
}

func (x *AccountPhone_SupportedActions) GetChange() bool {
	if x != nil {
		return x.Change
	}
	return false
}

func (x *AccountPhone_SupportedActions) GetLock() bool {
	if x != nil {
		return x.Lock
	}
	return false
}

func (x *AccountPhone_SupportedActions) GetUnlock() bool {
	if x != nil {
		return x.Unlock
	}
	return false
}

type AccountPhone_ApplicabilityLevels struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DefaultForOutboundCommunications ApplicabilityLevel `protobuf:"varint,2,opt,name=defaultForOutboundCommunications,proto3,enum=account.ApplicabilityLevel" json:"defaultForOutboundCommunications,omitempty"`
	ExpirationTime                   ApplicabilityLevel `protobuf:"varint,5,opt,name=expirationTime,proto3,enum=account.ApplicabilityLevel" json:"expirationTime,omitempty"`
	IsPermanent                      ApplicabilityLevel `protobuf:"varint,6,opt,name=isPermanent,proto3,enum=account.ApplicabilityLevel" json:"isPermanent,omitempty"`
}

func (x *AccountPhone_ApplicabilityLevels) Reset() {
	*x = AccountPhone_ApplicabilityLevels{}
	mi := &file_account_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountPhone_ApplicabilityLevels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountPhone_ApplicabilityLevels) ProtoMessage() {}

func (x *AccountPhone_ApplicabilityLevels) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountPhone_ApplicabilityLevels.ProtoReflect.Descriptor instead.
func (*AccountPhone_ApplicabilityLevels) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{8, 1}
}

func (x *AccountPhone_ApplicabilityLevels) GetDefaultForOutboundCommunications() ApplicabilityLevel {
	if x != nil {
		return x.DefaultForOutboundCommunications
	}
	return ApplicabilityLevel_UNKNOWN_APPLICABILITY_LEVEL
}

func (x *AccountPhone_ApplicabilityLevels) GetExpirationTime() ApplicabilityLevel {
	if x != nil {
		return x.ExpirationTime
	}
	return ApplicabilityLevel_UNKNOWN_APPLICABILITY_LEVEL
}

func (x *AccountPhone_ApplicabilityLevels) GetIsPermanent() ApplicabilityLevel {
	if x != nil {
		return x.IsPermanent
	}
	return ApplicabilityLevel_UNKNOWN_APPLICABILITY_LEVEL
}

var File_account_proto protoreflect.FileDescriptor

//go:embed account.pb.raw
var file_account_proto_rawDesc []byte

var (
	file_account_proto_rawDescOnce sync.Once
	file_account_proto_rawDescData = file_account_proto_rawDesc
)

func file_account_proto_rawDescGZIP() []byte {
	file_account_proto_rawDescOnce.Do(func() {
		file_account_proto_rawDescData = protoimpl.X.CompressGZIP(file_account_proto_rawDescData)
	})
	return file_account_proto_rawDescData
}

var file_account_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_account_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_account_proto_goTypes = []any{
	(ClientType)(0),                                            // 0: account.ClientType
	(ClientSetting)(0),                                         // 1: account.ClientSetting
	(ApplicabilityLevel)(0),                                    // 2: account.ApplicabilityLevel
	(SupportLevel)(0),                                          // 3: account.SupportLevel
	(CallAsPhone_DisplayHint)(0),                               // 4: account.CallAsPhone.DisplayHint
	(AccountPhone_Branding)(0),                                 // 5: account.AccountPhone.Branding
	(*Account)(nil),                                            // 6: account.Account
	(*AccountVersion)(nil),                                     // 7: account.AccountVersion
	(*Communication)(nil),                                      // 8: account.Communication
	(*Phone)(nil),                                              // 9: account.Phone
	(*LinkedPhoneRestrictions)(nil),                            // 10: account.LinkedPhoneRestrictions
	(*LinkedVoIPDevice)(nil),                                   // 11: account.LinkedVoIPDevice
	(*DefaultVoIPSettings)(nil),                                // 12: account.DefaultVoIPSettings
	(*CallAsPhone)(nil),                                        // 13: account.CallAsPhone
	(*AccountPhone)(nil),                                       // 14: account.AccountPhone
	(*PhoneNumber)(nil),                                        // 15: account.PhoneNumber
	(*Communication_DoNotDisturb)(nil),                         // 16: account.Communication.DoNotDisturb
	(*Communication_Transcription)(nil),                        // 17: account.Communication.Transcription
	(*Communication_SupportedActions)(nil),                     // 18: account.Communication.SupportedActions
	(*Communication_DoNotDisturb_ApplicabilityMask)(nil),       // 19: account.Communication.DoNotDisturb.ApplicabilityMask
	(*Communication_DoNotDisturb_ApplicabilityLevels)(nil),     // 20: account.Communication.DoNotDisturb.ApplicabilityLevels
	(*Communication_Transcription_ApplicabilityMask)(nil),      // 21: account.Communication.Transcription.ApplicabilityMask
	(*Communication_Transcription_ApplicabilityLevels)(nil),    // 22: account.Communication.Transcription.ApplicabilityLevels
	(*Communication_SupportedActions_ApplicabilityLevels)(nil), // 23: account.Communication.SupportedActions.ApplicabilityLevels
	(*LinkedPhoneRestrictions_CountryWhitelist)(nil),           // 24: account.LinkedPhoneRestrictions.CountryWhitelist
	(*AccountPhone_SupportedActions)(nil),                      // 25: account.AccountPhone.SupportedActions
	(*AccountPhone_ApplicabilityLevels)(nil),                   // 26: account.AccountPhone.ApplicabilityLevels
}
var file_account_proto_depIdxs = []int32{
	9,  // 0: account.Account.phones:type_name -> account.Phone
	8,  // 1: account.Account.communication:type_name -> account.Communication
	7,  // 2: account.Account.version:type_name -> account.AccountVersion
	16, // 3: account.Communication.doNotDisturb:type_name -> account.Communication.DoNotDisturb
	17, // 4: account.Communication.transcription:type_name -> account.Communication.Transcription
	18, // 5: account.Communication.supportedActions:type_name -> account.Communication.SupportedActions
	15, // 6: account.Communication.defaultOutboundCallerID:type_name -> account.PhoneNumber
	14, // 7: account.Phone.accountPhone:type_name -> account.AccountPhone
	10, // 8: account.Phone.linkedPhoneRestrictions:type_name -> account.LinkedPhoneRestrictions
	11, // 9: account.Phone.linkedVoIPDevices:type_name -> account.LinkedVoIPDevice
	12, // 10: account.Phone.defaultVoIPSettings:type_name -> account.DefaultVoIPSettings
	13, // 11: account.Phone.callAsPhone:type_name -> account.CallAsPhone
	24, // 12: account.LinkedPhoneRestrictions.countryWhitelist:type_name -> account.LinkedPhoneRestrictions.CountryWhitelist
	0,  // 13: account.LinkedVoIPDevice.clientType:type_name -> account.ClientType
	1,  // 14: account.LinkedVoIPDevice.inboundCalls:type_name -> account.ClientSetting
	1,  // 15: account.LinkedVoIPDevice.outboundCalls:type_name -> account.ClientSetting
	1,  // 16: account.DefaultVoIPSettings.preferVoIP:type_name -> account.ClientSetting
	15, // 17: account.CallAsPhone.phoneNumber:type_name -> account.PhoneNumber
	4,  // 18: account.CallAsPhone.displayHint:type_name -> account.CallAsPhone.DisplayHint
	15, // 19: account.AccountPhone.phoneNumber:type_name -> account.PhoneNumber
	5,  // 20: account.AccountPhone.branding:type_name -> account.AccountPhone.Branding
	25, // 21: account.AccountPhone.supportedActions:type_name -> account.AccountPhone.SupportedActions
	26, // 22: account.AccountPhone.applicabilityLevels:type_name -> account.AccountPhone.ApplicabilityLevels
	19, // 23: account.Communication.DoNotDisturb.applicabilityMask:type_name -> account.Communication.DoNotDisturb.ApplicabilityMask
	20, // 24: account.Communication.DoNotDisturb.applicabilityLevels:type_name -> account.Communication.DoNotDisturb.ApplicabilityLevels
	21, // 25: account.Communication.Transcription.applicabilityMask:type_name -> account.Communication.Transcription.ApplicabilityMask
	22, // 26: account.Communication.Transcription.applicabilityLevels:type_name -> account.Communication.Transcription.ApplicabilityLevels
	3,  // 27: account.Communication.SupportedActions.sendSMS:type_name -> account.SupportLevel
	3,  // 28: account.Communication.SupportedActions.makeEmergencyVoIPCall:type_name -> account.SupportLevel
	3,  // 29: account.Communication.SupportedActions.makeShortCodeProxyCall:type_name -> account.SupportLevel
	3,  // 30: account.Communication.SupportedActions.transferCall:type_name -> account.SupportLevel
	3,  // 31: account.Communication.SupportedActions.useHangoutsForCalling:type_name -> account.SupportLevel
	3,  // 32: account.Communication.SupportedActions.allowAllShortCodeDialing:type_name -> account.SupportLevel
	3,  // 33: account.Communication.SupportedActions.allowArbitraryPhoneNumberDialing:type_name -> account.SupportLevel
	23, // 34: account.Communication.SupportedActions.applicabilityLevels:type_name -> account.Communication.SupportedActions.ApplicabilityLevels
	2,  // 35: account.Communication.DoNotDisturb.ApplicabilityLevels.enabled:type_name -> account.ApplicabilityLevel
	2,  // 36: account.Communication.DoNotDisturb.ApplicabilityLevels.expiration:type_name -> account.ApplicabilityLevel
	2,  // 37: account.Communication.DoNotDisturb.ApplicabilityLevels.enableDndOutsideWorkHours:type_name -> account.ApplicabilityLevel
	2,  // 38: account.Communication.DoNotDisturb.ApplicabilityLevels.enableDndOutOfOffice:type_name -> account.ApplicabilityLevel
	2,  // 39: account.Communication.DoNotDisturb.ApplicabilityLevels.dndReason:type_name -> account.ApplicabilityLevel
	2,  // 40: account.Communication.DoNotDisturb.ApplicabilityLevels.allLines:type_name -> account.ApplicabilityLevel
	2,  // 41: account.Communication.DoNotDisturb.ApplicabilityLevels.directLines:type_name -> account.ApplicabilityLevel
	2,  // 42: account.Communication.DoNotDisturb.ApplicabilityLevels.allRgLines:type_name -> account.ApplicabilityLevel
	2,  // 43: account.Communication.Transcription.ApplicabilityLevels.enableForVoicemail:type_name -> account.ApplicabilityLevel
	2,  // 44: account.Communication.Transcription.ApplicabilityLevels.consentsToMachineAnalysis:type_name -> account.ApplicabilityLevel
	2,  // 45: account.Communication.SupportedActions.ApplicabilityLevels.useHangoutsForCalling:type_name -> account.ApplicabilityLevel
	2,  // 46: account.AccountPhone.ApplicabilityLevels.defaultForOutboundCommunications:type_name -> account.ApplicabilityLevel
	2,  // 47: account.AccountPhone.ApplicabilityLevels.expirationTime:type_name -> account.ApplicabilityLevel
	2,  // 48: account.AccountPhone.ApplicabilityLevels.isPermanent:type_name -> account.ApplicabilityLevel
	49, // [49:49] is the sub-list for method output_type
	49, // [49:49] is the sub-list for method input_type
	49, // [49:49] is the sub-list for extension type_name
	49, // [49:49] is the sub-list for extension extendee
	0,  // [0:49] is the sub-list for field type_name
}

func init() { file_account_proto_init() }
func file_account_proto_init() {
	if File_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_account_proto_rawDesc,
			NumEnums:      6,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_proto_goTypes,
		DependencyIndexes: file_account_proto_depIdxs,
		EnumInfos:         file_account_proto_enumTypes,
		MessageInfos:      file_account_proto_msgTypes,
	}.Build()
	File_account_proto = out.File
	file_account_proto_rawDesc = nil
	file_account_proto_goTypes = nil
	file_account_proto_depIdxs = nil
}
