// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: push.proto

package gvproto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqRegisterDestination struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Destination   *ReqRegisterDestination_Destination `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqRegisterDestination) Reset() {
	*x = ReqRegisterDestination{}
	mi := &file_push_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqRegisterDestination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqRegisterDestination) ProtoMessage() {}

func (x *ReqRegisterDestination) ProtoReflect() protoreflect.Message {
	mi := &file_push_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqRegisterDestination.ProtoReflect.Descriptor instead.
func (*ReqRegisterDestination) Descriptor() ([]byte, []int) {
	return file_push_proto_rawDescGZIP(), []int{0}
}

func (x *ReqRegisterDestination) GetDestination() *ReqRegisterDestination_Destination {
	if x != nil {
		return x.Destination
	}
	return nil
}

type RespRegisterDestination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespRegisterDestination) Reset() {
	*x = RespRegisterDestination{}
	mi := &file_push_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespRegisterDestination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespRegisterDestination) ProtoMessage() {}

func (x *RespRegisterDestination) ProtoReflect() protoreflect.Message {
	mi := &file_push_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespRegisterDestination.ProtoReflect.Descriptor instead.
func (*RespRegisterDestination) Descriptor() ([]byte, []int) {
	return file_push_proto_rawDescGZIP(), []int{1}
}

type ReqRegisterDestination_Destination struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	DeviceID      string                                  `protobuf:"bytes,12,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	Fcm           *ReqRegisterDestination_Destination_FCM `protobuf:"bytes,13,opt,name=fcm,proto3" json:"fcm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqRegisterDestination_Destination) Reset() {
	*x = ReqRegisterDestination_Destination{}
	mi := &file_push_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqRegisterDestination_Destination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqRegisterDestination_Destination) ProtoMessage() {}

func (x *ReqRegisterDestination_Destination) ProtoReflect() protoreflect.Message {
	mi := &file_push_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqRegisterDestination_Destination.ProtoReflect.Descriptor instead.
func (*ReqRegisterDestination_Destination) Descriptor() ([]byte, []int) {
	return file_push_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ReqRegisterDestination_Destination) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *ReqRegisterDestination_Destination) GetFcm() *ReqRegisterDestination_Destination_FCM {
	if x != nil {
		return x.Fcm
	}
	return nil
}

type ReqRegisterDestination_Destination_FCM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqRegisterDestination_Destination_FCM) Reset() {
	*x = ReqRegisterDestination_Destination_FCM{}
	mi := &file_push_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqRegisterDestination_Destination_FCM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqRegisterDestination_Destination_FCM) ProtoMessage() {}

func (x *ReqRegisterDestination_Destination_FCM) ProtoReflect() protoreflect.Message {
	mi := &file_push_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqRegisterDestination_Destination_FCM.ProtoReflect.Descriptor instead.
func (*ReqRegisterDestination_Destination_FCM) Descriptor() ([]byte, []int) {
	return file_push_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *ReqRegisterDestination_Destination_FCM) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_push_proto protoreflect.FileDescriptor

const file_push_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"push.proto\x12\x04push\"\xed\x01\n" +
	"\x16ReqRegisterDestination\x12J\n" +
	"\vdestination\x18\x02 \x01(\v2(.push.ReqRegisterDestination.DestinationR\vdestination\x1a\x86\x01\n" +
	"\vDestination\x12\x1a\n" +
	"\bdeviceID\x18\f \x01(\tR\bdeviceID\x12>\n" +
	"\x03fcm\x18\r \x01(\v2,.push.ReqRegisterDestination.Destination.FCMR\x03fcm\x1a\x1b\n" +
	"\x03FCM\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x19\n" +
	"\x17RespRegisterDestinationB\fZ\n" +
	"../gvprotob\x06proto3"

var (
	file_push_proto_rawDescOnce sync.Once
	file_push_proto_rawDescData []byte
)

func file_push_proto_rawDescGZIP() []byte {
	file_push_proto_rawDescOnce.Do(func() {
		file_push_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_push_proto_rawDesc), len(file_push_proto_rawDesc)))
	})
	return file_push_proto_rawDescData
}

var file_push_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_push_proto_goTypes = []any{
	(*ReqRegisterDestination)(nil),                 // 0: push.ReqRegisterDestination
	(*RespRegisterDestination)(nil),                // 1: push.RespRegisterDestination
	(*ReqRegisterDestination_Destination)(nil),     // 2: push.ReqRegisterDestination.Destination
	(*ReqRegisterDestination_Destination_FCM)(nil), // 3: push.ReqRegisterDestination.Destination.FCM
}
var file_push_proto_depIdxs = []int32{
	2, // 0: push.ReqRegisterDestination.destination:type_name -> push.ReqRegisterDestination.Destination
	3, // 1: push.ReqRegisterDestination.Destination.fcm:type_name -> push.ReqRegisterDestination.Destination.FCM
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_push_proto_init() }
func file_push_proto_init() {
	if File_push_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_push_proto_rawDesc), len(file_push_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_push_proto_goTypes,
		DependencyIndexes: file_push_proto_depIdxs,
		MessageInfos:      file_push_proto_msgTypes,
	}.Build()
	File_push_proto = out.File
	file_push_proto_goTypes = nil
	file_push_proto_depIdxs = nil
}
