// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: push.proto

package gvproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushRegistrationRequest struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Body          *PushRegistrationRequest_RequestBody `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRegistrationRequest) Reset() {
	*x = PushRegistrationRequest{}
	mi := &file_push_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRegistrationRequest) ProtoMessage() {}

func (x *PushRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_push_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRegistrationRequest.ProtoReflect.Descriptor instead.
func (*PushRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_push_proto_rawDescGZIP(), []int{0}
}

func (x *PushRegistrationRequest) GetBody() *PushRegistrationRequest_RequestBody {
	if x != nil {
		return x.Body
	}
	return nil
}

type PushRegistrationRequest_RequestBody struct {
	state         protoimpl.MessageState                        `protogen:"open.v1"`
	Hash          string                                        `protobuf:"bytes,12,opt,name=hash,proto3" json:"hash,omitempty"`
	Fcm           *PushRegistrationRequest_RequestBody_FCMToken `protobuf:"bytes,13,opt,name=fcm,proto3" json:"fcm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRegistrationRequest_RequestBody) Reset() {
	*x = PushRegistrationRequest_RequestBody{}
	mi := &file_push_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRegistrationRequest_RequestBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRegistrationRequest_RequestBody) ProtoMessage() {}

func (x *PushRegistrationRequest_RequestBody) ProtoReflect() protoreflect.Message {
	mi := &file_push_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRegistrationRequest_RequestBody.ProtoReflect.Descriptor instead.
func (*PushRegistrationRequest_RequestBody) Descriptor() ([]byte, []int) {
	return file_push_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PushRegistrationRequest_RequestBody) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *PushRegistrationRequest_RequestBody) GetFcm() *PushRegistrationRequest_RequestBody_FCMToken {
	if x != nil {
		return x.Fcm
	}
	return nil
}

type PushRegistrationRequest_RequestBody_FCMToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRegistrationRequest_RequestBody_FCMToken) Reset() {
	*x = PushRegistrationRequest_RequestBody_FCMToken{}
	mi := &file_push_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRegistrationRequest_RequestBody_FCMToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRegistrationRequest_RequestBody_FCMToken) ProtoMessage() {}

func (x *PushRegistrationRequest_RequestBody_FCMToken) ProtoReflect() protoreflect.Message {
	mi := &file_push_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRegistrationRequest_RequestBody_FCMToken.ProtoReflect.Descriptor instead.
func (*PushRegistrationRequest_RequestBody_FCMToken) Descriptor() ([]byte, []int) {
	return file_push_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *PushRegistrationRequest_RequestBody_FCMToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_push_proto protoreflect.FileDescriptor

const file_push_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"push.proto\x12\x04push\"\xe4\x01\n" +
	"\x17PushRegistrationRequest\x12=\n" +
	"\x04body\x18\x02 \x01(\v2).push.PushRegistrationRequest.RequestBodyR\x04body\x1a\x89\x01\n" +
	"\vRequestBody\x12\x12\n" +
	"\x04hash\x18\f \x01(\tR\x04hash\x12D\n" +
	"\x03fcm\x18\r \x01(\v22.push.PushRegistrationRequest.RequestBody.FCMTokenR\x03fcm\x1a \n" +
	"\bFCMToken\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05tokenB\fZ\n" +
	"../gvprotob\x06proto3"

var (
	file_push_proto_rawDescOnce sync.Once
	file_push_proto_rawDescData []byte
)

func file_push_proto_rawDescGZIP() []byte {
	file_push_proto_rawDescOnce.Do(func() {
		file_push_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_push_proto_rawDesc), len(file_push_proto_rawDesc)))
	})
	return file_push_proto_rawDescData
}

var file_push_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_push_proto_goTypes = []any{
	(*PushRegistrationRequest)(nil),                      // 0: push.PushRegistrationRequest
	(*PushRegistrationRequest_RequestBody)(nil),          // 1: push.PushRegistrationRequest.RequestBody
	(*PushRegistrationRequest_RequestBody_FCMToken)(nil), // 2: push.PushRegistrationRequest.RequestBody.FCMToken
}
var file_push_proto_depIdxs = []int32{
	1, // 0: push.PushRegistrationRequest.body:type_name -> push.PushRegistrationRequest.RequestBody
	2, // 1: push.PushRegistrationRequest.RequestBody.fcm:type_name -> push.PushRegistrationRequest.RequestBody.FCMToken
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_push_proto_init() }
func file_push_proto_init() {
	if File_push_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_push_proto_rawDesc), len(file_push_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_push_proto_goTypes,
		DependencyIndexes: file_push_proto_depIdxs,
		MessageInfos:      file_push_proto_msgTypes,
	}.Build()
	File_push_proto = out.File
	file_push_proto_goTypes = nil
	file_push_proto_depIdxs = nil
}
