// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.21.12
// source: requests.proto

package gvproto

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"

	_ "embed"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqSendSMS_Media_Type int32

const (
	ReqSendSMS_Media_UNKNOWN_TYPE ReqSendSMS_Media_Type = 0
	ReqSendSMS_Media_JPEG         ReqSendSMS_Media_Type = 1
	ReqSendSMS_Media_PNG          ReqSendSMS_Media_Type = 2
	ReqSendSMS_Media_TIFF         ReqSendSMS_Media_Type = 3
	ReqSendSMS_Media_GIF          ReqSendSMS_Media_Type = 4
	ReqSendSMS_Media_BMP          ReqSendSMS_Media_Type = 5
	ReqSendSMS_Media_WEBP         ReqSendSMS_Media_Type = 6
)

// Enum value maps for ReqSendSMS_Media_Type.
var (
	ReqSendSMS_Media_Type_name = map[int32]string{
		0: "UNKNOWN_TYPE",
		1: "JPEG",
		2: "PNG",
		3: "TIFF",
		4: "GIF",
		5: "BMP",
		6: "WEBP",
	}
	ReqSendSMS_Media_Type_value = map[string]int32{
		"UNKNOWN_TYPE": 0,
		"JPEG":         1,
		"PNG":          2,
		"TIFF":         3,
		"GIF":          4,
		"BMP":          5,
		"WEBP":         6,
	}
)

func (x ReqSendSMS_Media_Type) Enum() *ReqSendSMS_Media_Type {
	p := new(ReqSendSMS_Media_Type)
	*p = x
	return p
}

func (x ReqSendSMS_Media_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReqSendSMS_Media_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_requests_proto_enumTypes[0].Descriptor()
}

func (ReqSendSMS_Media_Type) Type() protoreflect.EnumType {
	return &file_requests_proto_enumTypes[0]
}

func (x ReqSendSMS_Media_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReqSendSMS_Media_Type.Descriptor instead.
func (ReqSendSMS_Media_Type) EnumDescriptor() ([]byte, []int) {
	return file_requests_proto_rawDescGZIP(), []int{1, 2, 0}
}

type ReqGetAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnknownInt2 int32 `protobuf:"varint,2,opt,name=unknownInt2,proto3" json:"unknownInt2,omitempty"` // 1
}

func (x *ReqGetAccount) Reset() {
	*x = ReqGetAccount{}
	mi := &file_requests_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqGetAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetAccount) ProtoMessage() {}

func (x *ReqGetAccount) ProtoReflect() protoreflect.Message {
	mi := &file_requests_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetAccount.ProtoReflect.Descriptor instead.
func (*ReqGetAccount) Descriptor() ([]byte, []int) {
	return file_requests_proto_rawDescGZIP(), []int{0}
}

func (x *ReqGetAccount) GetUnknownInt2() int32 {
	if x != nil {
		return x.UnknownInt2
	}
	return 0
}

type ReqSendSMS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text          string                   `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	ThreadID      string                   `protobuf:"bytes,6,opt,name=threadID,proto3" json:"threadID,omitempty"`
	Recipients    []string                 `protobuf:"bytes,7,rep,name=recipients,proto3" json:"recipients,omitempty"`
	TransactionID *ReqSendSMS_WrappedTxnID `protobuf:"bytes,9,opt,name=transactionID,proto3" json:"transactionID,omitempty"`
	Media         *ReqSendSMS_Media        `protobuf:"bytes,10,opt,name=media,proto3" json:"media,omitempty"`
	TrackingData  *ReqSendSMS_TrackingData `protobuf:"bytes,11,opt,name=trackingData,proto3" json:"trackingData,omitempty"`
}

func (x *ReqSendSMS) Reset() {
	*x = ReqSendSMS{}
	mi := &file_requests_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqSendSMS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSendSMS) ProtoMessage() {}

func (x *ReqSendSMS) ProtoReflect() protoreflect.Message {
	mi := &file_requests_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSendSMS.ProtoReflect.Descriptor instead.
func (*ReqSendSMS) Descriptor() ([]byte, []int) {
	return file_requests_proto_rawDescGZIP(), []int{1}
}

func (x *ReqSendSMS) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ReqSendSMS) GetThreadID() string {
	if x != nil {
		return x.ThreadID
	}
	return ""
}

func (x *ReqSendSMS) GetRecipients() []string {
	if x != nil {
		return x.Recipients
	}
	return nil
}

func (x *ReqSendSMS) GetTransactionID() *ReqSendSMS_WrappedTxnID {
	if x != nil {
		return x.TransactionID
	}
	return nil
}

func (x *ReqSendSMS) GetMedia() *ReqSendSMS_Media {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *ReqSendSMS) GetTrackingData() *ReqSendSMS_TrackingData {
	if x != nil {
		return x.TrackingData
	}
	return nil
}

type UnknownWrapper struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnknownInt2 int32 `protobuf:"varint,2,opt,name=unknownInt2,proto3" json:"unknownInt2,omitempty"` // 1
	UnknownInt3 int32 `protobuf:"varint,3,opt,name=unknownInt3,proto3" json:"unknownInt3,omitempty"` // 1
}

func (x *UnknownWrapper) Reset() {
	*x = UnknownWrapper{}
	mi := &file_requests_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnknownWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnknownWrapper) ProtoMessage() {}

func (x *UnknownWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_requests_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnknownWrapper.ProtoReflect.Descriptor instead.
func (*UnknownWrapper) Descriptor() ([]byte, []int) {
	return file_requests_proto_rawDescGZIP(), []int{2}
}

func (x *UnknownWrapper) GetUnknownInt2() int32 {
	if x != nil {
		return x.UnknownInt2
	}
	return 0
}

func (x *UnknownWrapper) GetUnknownInt3() int32 {
	if x != nil {
		return x.UnknownInt3
	}
	return 0
}

type ReqListThreads struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Folder         ThreadFolder    `protobuf:"varint,1,opt,name=folder,proto3,enum=threads.ThreadFolder" json:"folder,omitempty"`
	UnknownInt2    int32           `protobuf:"varint,2,opt,name=unknownInt2,proto3" json:"unknownInt2,omitempty"` // 10 or 20
	UnknownInt3    int32           `protobuf:"varint,3,opt,name=unknownInt3,proto3" json:"unknownInt3,omitempty"` // 15
	VersionToken   string          `protobuf:"bytes,5,opt,name=versionToken,proto3" json:"versionToken,omitempty"`
	UnknownWrapper *UnknownWrapper `protobuf:"bytes,6,opt,name=unknownWrapper,proto3" json:"unknownWrapper,omitempty"`
}

func (x *ReqListThreads) Reset() {
	*x = ReqListThreads{}
	mi := &file_requests_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqListThreads) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqListThreads) ProtoMessage() {}

func (x *ReqListThreads) ProtoReflect() protoreflect.Message {
	mi := &file_requests_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqListThreads.ProtoReflect.Descriptor instead.
func (*ReqListThreads) Descriptor() ([]byte, []int) {
	return file_requests_proto_rawDescGZIP(), []int{3}
}

func (x *ReqListThreads) GetFolder() ThreadFolder {
	if x != nil {
		return x.Folder
	}
	return ThreadFolder_UNKNOWN_THREAD_FOLDER
}

func (x *ReqListThreads) GetUnknownInt2() int32 {
	if x != nil {
		return x.UnknownInt2
	}
	return 0
}

func (x *ReqListThreads) GetUnknownInt3() int32 {
	if x != nil {
		return x.UnknownInt3
	}
	return 0
}

func (x *ReqListThreads) GetVersionToken() string {
	if x != nil {
		return x.VersionToken
	}
	return ""
}

func (x *ReqListThreads) GetUnknownWrapper() *UnknownWrapper {
	if x != nil {
		return x.UnknownWrapper
	}
	return nil
}

type ReqGetThread struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ThreadID          string          `protobuf:"bytes,1,opt,name=threadID,proto3" json:"threadID,omitempty"`
	MaybeMessageCount int32           `protobuf:"varint,2,opt,name=maybeMessageCount,proto3" json:"maybeMessageCount,omitempty"` // 100
	PaginationToken   string          `protobuf:"bytes,3,opt,name=paginationToken,proto3" json:"paginationToken,omitempty"`
	UnknownWrapper    *UnknownWrapper `protobuf:"bytes,4,opt,name=unknownWrapper,proto3" json:"unknownWrapper,omitempty"`
}

func (x *ReqGetThread) Reset() {
	*x = ReqGetThread{}
	mi := &file_requests_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqGetThread) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetThread) ProtoMessage() {}

func (x *ReqGetThread) ProtoReflect() protoreflect.Message {
	mi := &file_requests_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetThread.ProtoReflect.Descriptor instead.
func (*ReqGetThread) Descriptor() ([]byte, []int) {
	return file_requests_proto_rawDescGZIP(), []int{4}
}

func (x *ReqGetThread) GetThreadID() string {
	if x != nil {
		return x.ThreadID
	}
	return ""
}

func (x *ReqGetThread) GetMaybeMessageCount() int32 {
	if x != nil {
		return x.MaybeMessageCount
	}
	return 0
}

func (x *ReqGetThread) GetPaginationToken() string {
	if x != nil {
		return x.PaginationToken
	}
	return ""
}

func (x *ReqGetThread) GetUnknownWrapper() *UnknownWrapper {
	if x != nil {
		return x.UnknownWrapper
	}
	return nil
}

type ReqGetThreadingInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqGetThreadingInfo) Reset() {
	*x = ReqGetThreadingInfo{}
	mi := &file_requests_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqGetThreadingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetThreadingInfo) ProtoMessage() {}

func (x *ReqGetThreadingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_requests_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetThreadingInfo.ProtoReflect.Descriptor instead.
func (*ReqGetThreadingInfo) Descriptor() ([]byte, []int) {
	return file_requests_proto_rawDescGZIP(), []int{5}
}

type ReqUpdateAttributes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Attributes      *ThreadAttributes `protobuf:"bytes,1,opt,name=attributes,proto3" json:"attributes,omitempty"`
	OtherAttributes *ThreadAttributes `protobuf:"bytes,2,opt,name=otherAttributes,proto3" json:"otherAttributes,omitempty"`
	UnknownInt      int32             `protobuf:"varint,3,opt,name=unknownInt,proto3" json:"unknownInt,omitempty"`
}

func (x *ReqUpdateAttributes) Reset() {
	*x = ReqUpdateAttributes{}
	mi := &file_requests_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqUpdateAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUpdateAttributes) ProtoMessage() {}

func (x *ReqUpdateAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_requests_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUpdateAttributes.ProtoReflect.Descriptor instead.
func (*ReqUpdateAttributes) Descriptor() ([]byte, []int) {
	return file_requests_proto_rawDescGZIP(), []int{6}
}

func (x *ReqUpdateAttributes) GetAttributes() *ThreadAttributes {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *ReqUpdateAttributes) GetOtherAttributes() *ThreadAttributes {
	if x != nil {
		return x.OtherAttributes
	}
	return nil
}

func (x *ReqUpdateAttributes) GetUnknownInt() int32 {
	if x != nil {
		return x.UnknownInt
	}
	return 0
}

type ReqDeleteThread struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ThreadID string `protobuf:"bytes,1,opt,name=threadID,proto3" json:"threadID,omitempty"`
}

func (x *ReqDeleteThread) Reset() {
	*x = ReqDeleteThread{}
	mi := &file_requests_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqDeleteThread) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqDeleteThread) ProtoMessage() {}

func (x *ReqDeleteThread) ProtoReflect() protoreflect.Message {
	mi := &file_requests_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqDeleteThread.ProtoReflect.Descriptor instead.
func (*ReqDeleteThread) Descriptor() ([]byte, []int) {
	return file_requests_proto_rawDescGZIP(), []int{7}
}

func (x *ReqDeleteThread) GetThreadID() string {
	if x != nil {
		return x.ThreadID
	}
	return ""
}

type ReqAutocompleteContacts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnknownInt1  int32   `protobuf:"varint,1,opt,name=unknownInt1,proto3" json:"unknownInt1,omitempty"` // 243
	Query        string  `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	UnknownInts3 []int32 `protobuf:"varint,3,rep,packed,name=unknownInts3,proto3" json:"unknownInts3,omitempty"` // 1,2
	MaxResults   int32   `protobuf:"varint,4,opt,name=maxResults,proto3" json:"maxResults,omitempty"`            // 15 or 500
}

func (x *ReqAutocompleteContacts) Reset() {
	*x = ReqAutocompleteContacts{}
	mi := &file_requests_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqAutocompleteContacts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqAutocompleteContacts) ProtoMessage() {}

func (x *ReqAutocompleteContacts) ProtoReflect() protoreflect.Message {
	mi := &file_requests_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqAutocompleteContacts.ProtoReflect.Descriptor instead.
func (*ReqAutocompleteContacts) Descriptor() ([]byte, []int) {
	return file_requests_proto_rawDescGZIP(), []int{8}
}

func (x *ReqAutocompleteContacts) GetUnknownInt1() int32 {
	if x != nil {
		return x.UnknownInt1
	}
	return 0
}

func (x *ReqAutocompleteContacts) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ReqAutocompleteContacts) GetUnknownInts3() []int32 {
	if x != nil {
		return x.UnknownInts3
	}
	return nil
}

func (x *ReqAutocompleteContacts) GetMaxResults() int32 {
	if x != nil {
		return x.MaxResults
	}
	return 0
}

type ReqLookupContacts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnknownInt1  int32        `protobuf:"varint,1,opt,name=unknownInt1,proto3" json:"unknownInt1,omitempty"`          // 243
	UnknownInts2 []int32      `protobuf:"varint,2,rep,packed,name=unknownInts2,proto3" json:"unknownInts2,omitempty"` // 1,2
	Targets      []*ContactID `protobuf:"bytes,3,rep,name=targets,proto3" json:"targets,omitempty"`
}

func (x *ReqLookupContacts) Reset() {
	*x = ReqLookupContacts{}
	mi := &file_requests_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqLookupContacts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqLookupContacts) ProtoMessage() {}

func (x *ReqLookupContacts) ProtoReflect() protoreflect.Message {
	mi := &file_requests_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqLookupContacts.ProtoReflect.Descriptor instead.
func (*ReqLookupContacts) Descriptor() ([]byte, []int) {
	return file_requests_proto_rawDescGZIP(), []int{9}
}

func (x *ReqLookupContacts) GetUnknownInt1() int32 {
	if x != nil {
		return x.UnknownInt1
	}
	return 0
}

func (x *ReqLookupContacts) GetUnknownInts2() []int32 {
	if x != nil {
		return x.UnknownInts2
	}
	return nil
}

func (x *ReqLookupContacts) GetTargets() []*ContactID {
	if x != nil {
		return x.Targets
	}
	return nil
}

type ReqSendSMS_WrappedTxnID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *ReqSendSMS_WrappedTxnID) Reset() {
	*x = ReqSendSMS_WrappedTxnID{}
	mi := &file_requests_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqSendSMS_WrappedTxnID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSendSMS_WrappedTxnID) ProtoMessage() {}

func (x *ReqSendSMS_WrappedTxnID) ProtoReflect() protoreflect.Message {
	mi := &file_requests_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSendSMS_WrappedTxnID.ProtoReflect.Descriptor instead.
func (*ReqSendSMS_WrappedTxnID) Descriptor() ([]byte, []int) {
	return file_requests_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ReqSendSMS_WrappedTxnID) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type ReqSendSMS_TrackingData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ReqSendSMS_TrackingData) Reset() {
	*x = ReqSendSMS_TrackingData{}
	mi := &file_requests_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqSendSMS_TrackingData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSendSMS_TrackingData) ProtoMessage() {}

func (x *ReqSendSMS_TrackingData) ProtoReflect() protoreflect.Message {
	mi := &file_requests_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSendSMS_TrackingData.ProtoReflect.Descriptor instead.
func (*ReqSendSMS_TrackingData) Descriptor() ([]byte, []int) {
	return file_requests_proto_rawDescGZIP(), []int{1, 1}
}

func (x *ReqSendSMS_TrackingData) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type ReqSendSMS_Media struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type ReqSendSMS_Media_Type `protobuf:"varint,1,opt,name=type,proto3,enum=requests.ReqSendSMS_Media_Type" json:"type,omitempty"`
	URL  string                `protobuf:"bytes,4,opt,name=URL,proto3" json:"URL,omitempty"`
}

func (x *ReqSendSMS_Media) Reset() {
	*x = ReqSendSMS_Media{}
	mi := &file_requests_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqSendSMS_Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSendSMS_Media) ProtoMessage() {}

func (x *ReqSendSMS_Media) ProtoReflect() protoreflect.Message {
	mi := &file_requests_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSendSMS_Media.ProtoReflect.Descriptor instead.
func (*ReqSendSMS_Media) Descriptor() ([]byte, []int) {
	return file_requests_proto_rawDescGZIP(), []int{1, 2}
}

func (x *ReqSendSMS_Media) GetType() ReqSendSMS_Media_Type {
	if x != nil {
		return x.Type
	}
	return ReqSendSMS_Media_UNKNOWN_TYPE
}

func (x *ReqSendSMS_Media) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

var File_requests_proto protoreflect.FileDescriptor

//go:embed requests.pb.raw
var file_requests_proto_rawDesc []byte

var (
	file_requests_proto_rawDescOnce sync.Once
	file_requests_proto_rawDescData = file_requests_proto_rawDesc
)

func file_requests_proto_rawDescGZIP() []byte {
	file_requests_proto_rawDescOnce.Do(func() {
		file_requests_proto_rawDescData = protoimpl.X.CompressGZIP(file_requests_proto_rawDescData)
	})
	return file_requests_proto_rawDescData
}

var file_requests_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_requests_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_requests_proto_goTypes = []any{
	(ReqSendSMS_Media_Type)(0),      // 0: requests.ReqSendSMS.Media.Type
	(*ReqGetAccount)(nil),           // 1: requests.ReqGetAccount
	(*ReqSendSMS)(nil),              // 2: requests.ReqSendSMS
	(*UnknownWrapper)(nil),          // 3: requests.UnknownWrapper
	(*ReqListThreads)(nil),          // 4: requests.ReqListThreads
	(*ReqGetThread)(nil),            // 5: requests.ReqGetThread
	(*ReqGetThreadingInfo)(nil),     // 6: requests.ReqGetThreadingInfo
	(*ReqUpdateAttributes)(nil),     // 7: requests.ReqUpdateAttributes
	(*ReqDeleteThread)(nil),         // 8: requests.ReqDeleteThread
	(*ReqAutocompleteContacts)(nil), // 9: requests.ReqAutocompleteContacts
	(*ReqLookupContacts)(nil),       // 10: requests.ReqLookupContacts
	(*ReqSendSMS_WrappedTxnID)(nil), // 11: requests.ReqSendSMS.WrappedTxnID
	(*ReqSendSMS_TrackingData)(nil), // 12: requests.ReqSendSMS.TrackingData
	(*ReqSendSMS_Media)(nil),        // 13: requests.ReqSendSMS.Media
	(ThreadFolder)(0),               // 14: threads.ThreadFolder
	(*ThreadAttributes)(nil),        // 15: threads.ThreadAttributes
	(*ContactID)(nil),               // 16: contacts.ContactID
}
var file_requests_proto_depIdxs = []int32{
	11, // 0: requests.ReqSendSMS.transactionID:type_name -> requests.ReqSendSMS.WrappedTxnID
	13, // 1: requests.ReqSendSMS.media:type_name -> requests.ReqSendSMS.Media
	12, // 2: requests.ReqSendSMS.trackingData:type_name -> requests.ReqSendSMS.TrackingData
	14, // 3: requests.ReqListThreads.folder:type_name -> threads.ThreadFolder
	3,  // 4: requests.ReqListThreads.unknownWrapper:type_name -> requests.UnknownWrapper
	3,  // 5: requests.ReqGetThread.unknownWrapper:type_name -> requests.UnknownWrapper
	15, // 6: requests.ReqUpdateAttributes.attributes:type_name -> threads.ThreadAttributes
	15, // 7: requests.ReqUpdateAttributes.otherAttributes:type_name -> threads.ThreadAttributes
	16, // 8: requests.ReqLookupContacts.targets:type_name -> contacts.ContactID
	0,  // 9: requests.ReqSendSMS.Media.type:type_name -> requests.ReqSendSMS.Media.Type
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_requests_proto_init() }
func file_requests_proto_init() {
	if File_requests_proto != nil {
		return
	}
	file_threads_proto_init()
	file_contacts_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_requests_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_requests_proto_goTypes,
		DependencyIndexes: file_requests_proto_depIdxs,
		EnumInfos:         file_requests_proto_enumTypes,
		MessageInfos:      file_requests_proto_msgTypes,
	}.Build()
	File_requests_proto = out.File
	file_requests_proto_rawDesc = nil
	file_requests_proto_goTypes = nil
	file_requests_proto_depIdxs = nil
}
