// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: responses.proto

package gvproto

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"

	_ "embed"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RespGetThread struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Thread *Thread `protobuf:"bytes,1,opt,name=thread,proto3" json:"thread,omitempty"`
}

func (x *RespGetThread) Reset() {
	*x = RespGetThread{}
	if protoimpl.UnsafeEnabled {
		mi := &file_responses_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespGetThread) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespGetThread) ProtoMessage() {}

func (x *RespGetThread) ProtoReflect() protoreflect.Message {
	mi := &file_responses_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespGetThread.ProtoReflect.Descriptor instead.
func (*RespGetThread) Descriptor() ([]byte, []int) {
	return file_responses_proto_rawDescGZIP(), []int{0}
}

func (x *RespGetThread) GetThread() *Thread {
	if x != nil {
		return x.Thread
	}
	return nil
}

type RespListThreads struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Threads      []*Thread `protobuf:"bytes,1,rep,name=threads,proto3" json:"threads,omitempty"`
	VersionToken string    `protobuf:"bytes,3,opt,name=versionToken,proto3" json:"versionToken,omitempty"`
}

func (x *RespListThreads) Reset() {
	*x = RespListThreads{}
	if protoimpl.UnsafeEnabled {
		mi := &file_responses_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespListThreads) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespListThreads) ProtoMessage() {}

func (x *RespListThreads) ProtoReflect() protoreflect.Message {
	mi := &file_responses_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespListThreads.ProtoReflect.Descriptor instead.
func (*RespListThreads) Descriptor() ([]byte, []int) {
	return file_responses_proto_rawDescGZIP(), []int{1}
}

func (x *RespListThreads) GetThreads() []*Thread {
	if x != nil {
		return x.Threads
	}
	return nil
}

func (x *RespListThreads) GetVersionToken() string {
	if x != nil {
		return x.VersionToken
	}
	return ""
}

type RespSendSMS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ThreadID      string         `protobuf:"bytes,2,opt,name=threadID,proto3" json:"threadID,omitempty"`
	ThreadItemID  string         `protobuf:"bytes,3,opt,name=threadItemID,proto3" json:"threadItemID,omitempty"`
	TimestampMS   int64          `protobuf:"varint,4,opt,name=timestampMS,proto3" json:"timestampMS,omitempty"`
	ThreadFolders []ThreadFolder `protobuf:"varint,5,rep,packed,name=threadFolders,proto3,enum=threads.ThreadFolder" json:"threadFolders,omitempty"`
}

func (x *RespSendSMS) Reset() {
	*x = RespSendSMS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_responses_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespSendSMS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespSendSMS) ProtoMessage() {}

func (x *RespSendSMS) ProtoReflect() protoreflect.Message {
	mi := &file_responses_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespSendSMS.ProtoReflect.Descriptor instead.
func (*RespSendSMS) Descriptor() ([]byte, []int) {
	return file_responses_proto_rawDescGZIP(), []int{2}
}

func (x *RespSendSMS) GetThreadID() string {
	if x != nil {
		return x.ThreadID
	}
	return ""
}

func (x *RespSendSMS) GetThreadItemID() string {
	if x != nil {
		return x.ThreadItemID
	}
	return ""
}

func (x *RespSendSMS) GetTimestampMS() int64 {
	if x != nil {
		return x.TimestampMS
	}
	return 0
}

func (x *RespSendSMS) GetThreadFolders() []ThreadFolder {
	if x != nil {
		return x.ThreadFolders
	}
	return nil
}

type RespUpdateAttributes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Attributes *ThreadAttributes `protobuf:"bytes,1,opt,name=attributes,proto3" json:"attributes,omitempty"`
}

func (x *RespUpdateAttributes) Reset() {
	*x = RespUpdateAttributes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_responses_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespUpdateAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespUpdateAttributes) ProtoMessage() {}

func (x *RespUpdateAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_responses_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespUpdateAttributes.ProtoReflect.Descriptor instead.
func (*RespUpdateAttributes) Descriptor() ([]byte, []int) {
	return file_responses_proto_rawDescGZIP(), []int{3}
}

func (x *RespUpdateAttributes) GetAttributes() *ThreadAttributes {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type RespBatchUpdateAttributes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items *RespUpdateAttributes `protobuf:"bytes,1,opt,name=items,proto3" json:"items,omitempty"`
}

func (x *RespBatchUpdateAttributes) Reset() {
	*x = RespBatchUpdateAttributes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_responses_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespBatchUpdateAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespBatchUpdateAttributes) ProtoMessage() {}

func (x *RespBatchUpdateAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_responses_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespBatchUpdateAttributes.ProtoReflect.Descriptor instead.
func (*RespBatchUpdateAttributes) Descriptor() ([]byte, []int) {
	return file_responses_proto_rawDescGZIP(), []int{4}
}

func (x *RespBatchUpdateAttributes) GetItems() *RespUpdateAttributes {
	if x != nil {
		return x.Items
	}
	return nil
}

type RespGetAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
}

func (x *RespGetAccount) Reset() {
	*x = RespGetAccount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_responses_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespGetAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespGetAccount) ProtoMessage() {}

func (x *RespGetAccount) ProtoReflect() protoreflect.Message {
	mi := &file_responses_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespGetAccount.ProtoReflect.Descriptor instead.
func (*RespGetAccount) Descriptor() ([]byte, []int) {
	return file_responses_proto_rawDescGZIP(), []int{5}
}

func (x *RespGetAccount) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type RespDeleteThread struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RespDeleteThread) Reset() {
	*x = RespDeleteThread{}
	if protoimpl.UnsafeEnabled {
		mi := &file_responses_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespDeleteThread) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespDeleteThread) ProtoMessage() {}

func (x *RespDeleteThread) ProtoReflect() protoreflect.Message {
	mi := &file_responses_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespDeleteThread.ProtoReflect.Descriptor instead.
func (*RespDeleteThread) Descriptor() ([]byte, []int) {
	return file_responses_proto_rawDescGZIP(), []int{6}
}

var File_responses_proto protoreflect.FileDescriptor

//go:embed responses.pb.raw
var file_responses_proto_rawDesc []byte

var (
	file_responses_proto_rawDescOnce sync.Once
	file_responses_proto_rawDescData = file_responses_proto_rawDesc
)

func file_responses_proto_rawDescGZIP() []byte {
	file_responses_proto_rawDescOnce.Do(func() {
		file_responses_proto_rawDescData = protoimpl.X.CompressGZIP(file_responses_proto_rawDescData)
	})
	return file_responses_proto_rawDescData
}

var file_responses_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_responses_proto_goTypes = []any{
	(*RespGetThread)(nil),             // 0: responses.RespGetThread
	(*RespListThreads)(nil),           // 1: responses.RespListThreads
	(*RespSendSMS)(nil),               // 2: responses.RespSendSMS
	(*RespUpdateAttributes)(nil),      // 3: responses.RespUpdateAttributes
	(*RespBatchUpdateAttributes)(nil), // 4: responses.RespBatchUpdateAttributes
	(*RespGetAccount)(nil),            // 5: responses.RespGetAccount
	(*RespDeleteThread)(nil),          // 6: responses.RespDeleteThread
	(*Thread)(nil),                    // 7: threads.Thread
	(ThreadFolder)(0),                 // 8: threads.ThreadFolder
	(*ThreadAttributes)(nil),          // 9: threads.ThreadAttributes
	(*Account)(nil),                   // 10: account.Account
}
var file_responses_proto_depIdxs = []int32{
	7,  // 0: responses.RespGetThread.thread:type_name -> threads.Thread
	7,  // 1: responses.RespListThreads.threads:type_name -> threads.Thread
	8,  // 2: responses.RespSendSMS.threadFolders:type_name -> threads.ThreadFolder
	9,  // 3: responses.RespUpdateAttributes.attributes:type_name -> threads.ThreadAttributes
	3,  // 4: responses.RespBatchUpdateAttributes.items:type_name -> responses.RespUpdateAttributes
	10, // 5: responses.RespGetAccount.account:type_name -> account.Account
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_responses_proto_init() }
func file_responses_proto_init() {
	if File_responses_proto != nil {
		return
	}
	file_threads_proto_init()
	file_account_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_responses_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*RespGetThread); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_responses_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*RespListThreads); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_responses_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*RespSendSMS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_responses_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*RespUpdateAttributes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_responses_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*RespBatchUpdateAttributes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_responses_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*RespGetAccount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_responses_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*RespDeleteThread); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_responses_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_responses_proto_goTypes,
		DependencyIndexes: file_responses_proto_depIdxs,
		MessageInfos:      file_responses_proto_msgTypes,
	}.Build()
	File_responses_proto = out.File
	file_responses_proto_rawDesc = nil
	file_responses_proto_goTypes = nil
	file_responses_proto_depIdxs = nil
}
