// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.21.12
// source: waa.proto

package gvproto

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"

	_ "embed"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqCreateWaa struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestKey string `protobuf:"bytes,1,opt,name=requestKey,proto3" json:"requestKey,omitempty"`
}

func (x *ReqCreateWaa) Reset() {
	*x = ReqCreateWaa{}
	mi := &file_waa_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqCreateWaa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqCreateWaa) ProtoMessage() {}

func (x *ReqCreateWaa) ProtoReflect() protoreflect.Message {
	mi := &file_waa_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqCreateWaa.ProtoReflect.Descriptor instead.
func (*ReqCreateWaa) Descriptor() ([]byte, []int) {
	return file_waa_proto_rawDescGZIP(), []int{0}
}

func (x *ReqCreateWaa) GetRequestKey() string {
	if x != nil {
		return x.RequestKey
	}
	return ""
}

type ReqPingWaa struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestKey string `protobuf:"bytes,1,opt,name=requestKey,proto3" json:"requestKey,omitempty"`
	Payload    string `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	I1         int64  `protobuf:"varint,3,opt,name=i1,proto3" json:"i1,omitempty"`
	I2         int64  `protobuf:"varint,4,opt,name=i2,proto3" json:"i2,omitempty"`
}

func (x *ReqPingWaa) Reset() {
	*x = ReqPingWaa{}
	mi := &file_waa_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqPingWaa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqPingWaa) ProtoMessage() {}

func (x *ReqPingWaa) ProtoReflect() protoreflect.Message {
	mi := &file_waa_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqPingWaa.ProtoReflect.Descriptor instead.
func (*ReqPingWaa) Descriptor() ([]byte, []int) {
	return file_waa_proto_rawDescGZIP(), []int{1}
}

func (x *ReqPingWaa) GetRequestKey() string {
	if x != nil {
		return x.RequestKey
	}
	return ""
}

func (x *ReqPingWaa) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *ReqPingWaa) GetI1() int64 {
	if x != nil {
		return x.I1
	}
	return 0
}

func (x *ReqPingWaa) GetI2() int64 {
	if x != nil {
		return x.I2
	}
	return 0
}

type RespCreateWaa struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Waa *CreatedWaa `protobuf:"bytes,1,opt,name=waa,proto3" json:"waa,omitempty"`
}

func (x *RespCreateWaa) Reset() {
	*x = RespCreateWaa{}
	mi := &file_waa_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespCreateWaa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespCreateWaa) ProtoMessage() {}

func (x *RespCreateWaa) ProtoReflect() protoreflect.Message {
	mi := &file_waa_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespCreateWaa.ProtoReflect.Descriptor instead.
func (*RespCreateWaa) Descriptor() ([]byte, []int) {
	return file_waa_proto_rawDescGZIP(), []int{2}
}

func (x *RespCreateWaa) GetWaa() *CreatedWaa {
	if x != nil {
		return x.Waa
	}
	return nil
}

type RespPingWaa struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RespPingWaa) Reset() {
	*x = RespPingWaa{}
	mi := &file_waa_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespPingWaa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespPingWaa) ProtoMessage() {}

func (x *RespPingWaa) ProtoReflect() protoreflect.Message {
	mi := &file_waa_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespPingWaa.ProtoReflect.Descriptor instead.
func (*RespPingWaa) Descriptor() ([]byte, []int) {
	return file_waa_proto_rawDescGZIP(), []int{3}
}

type CreatedWaa struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RespID string `protobuf:"bytes,1,opt,name=respID,proto3" json:"respID,omitempty"`
	// When using binary protobuf, these are offset down by 1 and there's no respID
	InterpreterURL  *CreatedWaa_InterpreterURL `protobuf:"bytes,3,opt,name=interpreterURL,proto3" json:"interpreterURL,omitempty"`
	InterpreterHash string                     `protobuf:"bytes,4,opt,name=interpreterHash,proto3" json:"interpreterHash,omitempty"`
	Program         string                     `protobuf:"bytes,5,opt,name=program,proto3" json:"program,omitempty"`
	GlobalName      string                     `protobuf:"bytes,6,opt,name=globalName,proto3" json:"globalName,omitempty"`
}

func (x *CreatedWaa) Reset() {
	*x = CreatedWaa{}
	mi := &file_waa_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatedWaa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatedWaa) ProtoMessage() {}

func (x *CreatedWaa) ProtoReflect() protoreflect.Message {
	mi := &file_waa_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatedWaa.ProtoReflect.Descriptor instead.
func (*CreatedWaa) Descriptor() ([]byte, []int) {
	return file_waa_proto_rawDescGZIP(), []int{4}
}

func (x *CreatedWaa) GetRespID() string {
	if x != nil {
		return x.RespID
	}
	return ""
}

func (x *CreatedWaa) GetInterpreterURL() *CreatedWaa_InterpreterURL {
	if x != nil {
		return x.InterpreterURL
	}
	return nil
}

func (x *CreatedWaa) GetInterpreterHash() string {
	if x != nil {
		return x.InterpreterHash
	}
	return ""
}

func (x *CreatedWaa) GetProgram() string {
	if x != nil {
		return x.Program
	}
	return ""
}

func (x *CreatedWaa) GetGlobalName() string {
	if x != nil {
		return x.GlobalName
	}
	return ""
}

type CreatedWaa_InterpreterURL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	URL string `protobuf:"bytes,4,opt,name=URL,proto3" json:"URL,omitempty"`
}

func (x *CreatedWaa_InterpreterURL) Reset() {
	*x = CreatedWaa_InterpreterURL{}
	mi := &file_waa_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatedWaa_InterpreterURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatedWaa_InterpreterURL) ProtoMessage() {}

func (x *CreatedWaa_InterpreterURL) ProtoReflect() protoreflect.Message {
	mi := &file_waa_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatedWaa_InterpreterURL.ProtoReflect.Descriptor instead.
func (*CreatedWaa_InterpreterURL) Descriptor() ([]byte, []int) {
	return file_waa_proto_rawDescGZIP(), []int{4, 0}
}

func (x *CreatedWaa_InterpreterURL) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

var File_waa_proto protoreflect.FileDescriptor

//go:embed waa.pb.raw
var file_waa_proto_rawDesc []byte

var (
	file_waa_proto_rawDescOnce sync.Once
	file_waa_proto_rawDescData = file_waa_proto_rawDesc
)

func file_waa_proto_rawDescGZIP() []byte {
	file_waa_proto_rawDescOnce.Do(func() {
		file_waa_proto_rawDescData = protoimpl.X.CompressGZIP(file_waa_proto_rawDescData)
	})
	return file_waa_proto_rawDescData
}

var file_waa_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_waa_proto_goTypes = []any{
	(*ReqCreateWaa)(nil),              // 0: waa.ReqCreateWaa
	(*ReqPingWaa)(nil),                // 1: waa.ReqPingWaa
	(*RespCreateWaa)(nil),             // 2: waa.RespCreateWaa
	(*RespPingWaa)(nil),               // 3: waa.RespPingWaa
	(*CreatedWaa)(nil),                // 4: waa.CreatedWaa
	(*CreatedWaa_InterpreterURL)(nil), // 5: waa.CreatedWaa.InterpreterURL
}
var file_waa_proto_depIdxs = []int32{
	4, // 0: waa.RespCreateWaa.waa:type_name -> waa.CreatedWaa
	5, // 1: waa.CreatedWaa.interpreterURL:type_name -> waa.CreatedWaa.InterpreterURL
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_waa_proto_init() }
func file_waa_proto_init() {
	if File_waa_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_waa_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_waa_proto_goTypes,
		DependencyIndexes: file_waa_proto_depIdxs,
		MessageInfos:      file_waa_proto_msgTypes,
	}.Build()
	File_waa_proto = out.File
	file_waa_proto_rawDesc = nil
	file_waa_proto_goTypes = nil
	file_waa_proto_depIdxs = nil
}
